---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, agent, amazon fsx for ontap, azure netapp files, cloud sync, e-series, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery, netapp console, console' 
summary: NetApp Consoleの一部である機能とデータ サービスに対する最新の変更について説明します。 
---
= NetApp Consoleの最近の変更
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Consoleの一部である機能とデータ サービスに対する最新の変更について説明します。完全なリリース履歴については、link:release-notes-index.html["リリースノート全文"]個々のサービスごとに。



== 廃止されたサービス



=== エッジキャッシュ

エッジ キャッシング サービスは 2024 年 8 月 7 日に削除されました。



=== Kubernetes

Kubernetes クラスターの検出と管理のサポートは、2024 年 8 月 7 日に削除されました。



=== 移行レポート

移行レポート サービスは 2024 年 8 月 7 日に削除されました。



=== 運用の回復力

運用回復力機能は 2025 年 8 月 22 日に削除されました。



=== 修正策

修復サービスは 2024 年 4 月 22 日に削除されました。



== 2026年1月19日



=== バックアップとリカバリ



==== ONTAPボリュームワークロードの機能強化

このリリースのONTAPボリューム ワークロードでは、次の拡張機能が導入されています。

*複数のバケットのサポート*: (プライベート プレビュー) ONTAP 9.17.1 以降では、異なるクラウド プロバイダーにまたがるシステムごとに最大 6 つのバケットを使用して、システム内のボリュームを保護できるようになりました。

link:prev-ontap-backup-manage.html["NetApp Backup and Recoveryを使用したONTAPボリュームデータのバックアップの詳細"]。



==== VMwareワークロードの機能強化

この VMware ワークロードのリリースでは、次の拡張機能が導入されています。

* VMware ワークロード サポートが、NetApp Backup and Recovery で一般提供（GA）されました。
* ゲスト OS のファイルとフォルダーを復元できるようになりました。


https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-restore-guest-files-and-folders-overview.html["ゲストファイルとフォルダの復元の詳細"]。



==== Hyper-V ワークロードのプレビュー機能強化

このリリースの Hyper-V ワークロードでは、次の拡張機能が導入されています。

* Hyper-V VMのバックアップとスナップショットを別の場所に復元できるようになりました。この機能を使用して、異なるHyper-Vホスト上のVMバージョンを管理できます。
* NetApp Backup and Recovery では、System Center Virtual Machine Manager（SCVMM）によってプロビジョニングされ、CIFS 共有でホストされている Hyper-V 仮想マシンがサポートされるようになりました。
* 保護グループを編集できるようになりました。



NOTE: このリリースでのみ、[アクション] メニューの [アップグレード] オプションを使用して、Hyper-V または Windows 用のNetAppプラグインをアップグレードすることはできません。代わりに、各 Hyper-V ホストを削除し、再度追加してプラグインを更新します。

https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-restore.html["NetApp Backup and Recoveryを使用したHyper-V VMの復元の詳細"]。



==== KVM ワークロードのプレビュー機能強化

KVM ワークロード プレビューでは、Apache CloudStack によって管理される KVM ホストと仮想マシンが保護されるようになりました。

KVMワークロードの保護の詳細については、以下を参照してください。 https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kvm-protect-overview.html["KVM ワークロードの保護の概要"] 。



=== ランサムウェア耐性



==== サポートされていないボリューム

ランサムウェア耐性レポートでは、**概要** レポートでサポートされているボリュームとサポートされていないボリュームに関する情報が取得されるようになりました。この情報を使用して、システム内のボリュームがランサムウェア保護の対象外となる理由を診断します。

詳細については、 link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-reports.html["ランサムウェア耐性レポートをダウンロード"^]。



=== Keystone

NetApp ConsoleのKeystoneダッシュボードの更新:



==== サブスクリプションを変更できません

Keystoneサブスクリプションのコミット容量を変更するオプションは現在利用できません。この機能は将来のリリースで再導入される予定です。



== 2026年1月14日



=== データ分類



==== バージョン1.50

この Data Classification リリースには、バグ修正と次の更新が含まれています。

.カスタム分類の改善
データ分類では、データのカスタム カテゴリの作成がサポートされるようになりました。ファイルをアップロードして、データ分類がデータにカテゴリ マーカーを適用するために使用する AI モデルを微調整できます。すべてのカスタム分類のインターフェースが改善されました。

詳細については、 link:https://docs.netapp.com/us-en/data-services-data-classification/task-custom-classification.html["カスタム分類を作成する"^]。

.カスタムの古いデータ定義
データ分類では、組織のニーズに合わせて古いデータの定義をカスタマイズできるようになりました。以前は、古いデータは 3 年前に最後に変更されたデータとして定義されていました。現在では、最後にアクセスされた日時、または最後に変更された日時に基づいて古いデータを識別できます。期間は 6 か月前から 10 年前までの範囲です。

詳細については、 link:https://docs.netapp.com/us-en/data-services-data-classification/task-stale-data.html["古いデータ定義をカスタマイズする"^]。

.パフォーマンスの向上
データ分類、データ マッピング レポート、および調査ページのフィルターのすべてのページの読み込み時間が短縮されました。

.調査報告書の所要時間の見積もり
調査レポートをダウンロードすると、データ分類ではダウンロードが完了するまでの予想時間が表示されるようになりました。



== 2026年1月12日



=== コンソールのセットアップと管理



==== コンソールエージェント 4.3.0

4.3.0 リリースでは、標準モードと制限モードの両方がサポートされています。

コンソール エージェントのこのリリースには、セキュリティの改善、バグ修正、および次の機能が含まれています。

.コンソールエージェントのネットワーク接続を検証する機能
接続された Console エージェントのネットワーク接続をNetApp Console から直接検証できるようになりました。この機能は、Console エージェントの接続性を検証し、問題のトラブルシューティングに役立ちます。これは、Console エージェントのメンテナンスコンソールのコマンドラインインターフェース（CLI）からネットワーク診断を実行できる既存の機能に加えて提供されます。

link:https://docs.netapp.com/us-en/console-setup-admin/task-troubleshoot-agent.html#verify-network-access["NetApp Consoleから構成を実行する方法を学習します。"]



==== NetApp Console管理

このリリースには以下が含まれます。

.NetApp Consoleでのフェデレーション グループに対するロールベースのアクセス
NetApp Consoleは、フェデレーション グループ (Active Directory グループなど) へのロールの割り当てをサポートしており、管理者は組織の ID プロバイダー (IdP) のグループ メンバーシップに基づいてユーザーのオンボーディングとオフボーディングを自動化できます。この機能により、管理オーバーヘッドが削減され、グループ メンバーシップの変更に応じてコンソール アクセスが即座に更新されるため、安全で一貫したアクセスが確保されます。

link:https://docs.netapp.com/us-en/console-setup-admin/task-iam-manage-members-permissions.html#add-a-federated-group-to-your-organization["組織にフェデレーション グループへのアクセスを提供する方法を学習します。"]

.NetApp Consoleが制限モードの場合のフェデレーションのサポート
制限モードになっているNetApp Console組織に対してフェデレーションを有効にできるようになりました。これにより、ユーザーは制限モードのセキュリティ上の利点を維持しながら、企業の資格情報を使用してコンソールにログインできるようになります。

.読み取り専用モード
NetApp Console組織を読み取り専用モードに設定できます。読み取り専用モードでは、ユーザーはリソースと設定を表示できますが、変更することはできません。組織管理者またはスーパー管理者は、組織に対して読み取り専用モードを有効にすることができます。読み取り専用モードが有効になっている場合、管理者ロールを持つユーザーは、必要に応じて変更を加えるために手動で権限を昇格する必要があります。

link:https://docs.netapp.com/us-en/console-setup-admin/task-enable-read-only-mode.html["コンソール組織で読み取り専用モードを有効にする方法を学習します。"]

link:https://docs.netapp.com/us-en/console-setup-admin/task-user-settings.html["組織が読み取り専用モードの場合に役割を昇格させる方法を学習します。"]



=== ディザスタ リカバリ



==== オンプレミス環境での複数のコンソール エージェントのサポート

オンプレミスでDisaster Recovery を使用している場合は、vCenter インスタンスごとにコンソール エージェントを展開して、回復力を向上させることができます。

たとえば、2 つのサイト (サイト A とサイト B) がある場合、サイト A には、vCenter 1、 ONTAPデプロイメント 1、およびONTAPデプロイメント 2 に接続されたコンソール エージェント A を配置できます。サイト B には、vCenter 2 とONTAPデプロイメント 3 および 4 に接続されたコンソール エージェント B を配置できます。

災害復旧のコンソールエージェントの詳細については、以下を参照してください。 link:https://docs.netapp.com/us-en/data-services-disaster-recovery/get-started/dr-prerequisites.html#netapp-console-prerequisites["コンソールエージェントを作成する"^]。



==== データストアベースの保護を使用したレプリケーション プランのフェイルオーバー後に VM を追加する

フェイルオーバーがトリガーされると、データストアベースの保護を使用するすべてのレプリケーション プランには、データストアに追加された VM が含まれます (検出された場合)。フェイルオーバーが完了する前に、追加された VM のマッピングの詳細を提供する必要があります。

詳細については、 link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/failover.html["フェイルオーバーアプリケーション"^]。



==== 新しいメール通知

災害復旧では、次のイベントに関する電子メール通知が提供されるようになりました。

* 容量使用制限に近づいています
* レポート生成が完了しました
* 仕事の失敗
* ライセンスの有効期限または違反




==== Swaggerの改善

これで、Disaster Recovery 内から Swagger ドキュメントにアクセスできるようになりました。災害復旧で、**設定** を選択し、次に **API ドキュメント** を選択して Swagger にリンクするか、ブラウザのシークレット/プライベート モードで次の URL にアクセスします。 link:https://snapcenter.cloudmanager.cloud.netapp.com/api/api-doc/draas["https://snapcenter.cloudmanager.cloud.netapp.com/api/api-doc/draas"^]。



==== 改善されたユーザーインターフェース

災害復旧では、警告とエラー解決が改善されました。このリリースでは、キャンセルされたジョブがユーザー インターフェイスに表示されないエラーが修正されました。キャンセルされたジョブが表示されるようになりました。同じ宛先ネットワークが複数の異なるソース ネットワークにマップされている場合にも、新しい警告が表示されます。



==== レプリケーション プランに VM フォルダ構造の保持がデフォルトとして追加されました

レプリケーションを作成すると、新しいデフォルトでは VM フォルダー構造が保持されます。リカバリ対象に元のフォルダ階層がない場合、Disaster Recovery によってそれが作成されます。このオプションを選択解除すると、元のフォルダー階層を無視できます。

詳細については、 link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html["レプリケーションプランを作成する"^]。



=== ランサムウェア耐性



==== スナップショットをONTAPに複製する

Ransomware Resilience では、セカンダリONTAPサイトへのスナップショットのレプリケーションの追加がサポートされるようになりました。レプリケーション ポリシーを使用する保護グループを使用すると、ワークロードごとに同じ宛先または異なる宛先にレプリケートできます。レプリケーションを含むランサムウェア保護戦略を作成することも、定義済みの戦略を使用することもできます。

詳細については、 link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-protect.html["ランサムウェア耐性でワークロードを保護する"^]。



==== ランサムウェア耐性からワークロードを除外する

ランサムウェア耐性では、システム内の特定のワークロードを保護およびランサムウェア耐性ダッシュボードから除外することがサポートされるようになりました。検出後にワークロードを除外し、ランサムウェア保護を追加する場合は再度含めることができます。除外されたワークロードについては課金されません。

詳細については、 link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-start-discover.html#exclude-workloads["ワークロードを除外する"^]。



==== アラートをレビュー中としてマークする

Ransomware Resilience では、アラートを「レビュー中」としてマークできるようになりました。「レビュー中」ラベルを使用すると、アクティブなランサムウェアの脅威をトリアージおよび管理する際に、チーム全体の明確性が向上します。

詳細については、 link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-alert.html["ランサムウェア耐性のアラートを管理する"^]。



=== Cloud Volumes ONTAP



==== Cloud Volumes ONTAPの推奨課金オプション

Cloud Volumes ONTAPの使用量と超過分を計算するための優先課金オプションを選択できるようになりました。2025 年 6 月 25 日に Bring Your Own Licenses (BYOL)ライセンス モデルが限定的に利用可能になって以来、 NetApp はNetApp Consoleの *ライセンスとサブスクリプション* セクションに推奨される課金方法を追加しました。請求と超過料金については、年間マーケットプレイス サブスクリプションを使用するか、既存の BYOL モデルを優先オプションとして使用できます。これにより、組織の財務戦略と使用パターンに最適な課金方法を柔軟に選択できるようになります。

https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing-charging.html#billing-preferences-and-overages["請求設定と超過料金"^]。



== 2025年12月10日



=== コンソールのセットアップと管理



==== コンソールエージェント 4.2.0

4.2.0 リリースでは、標準モードと制限モードの両方がサポートされています。

コンソール エージェントのこのリリースには、セキュリティの改善、バグ修正、および次の機能が含まれています。

.Google Cloud Infrastructure Manager のサポート
NetApp、Google Cloud でエージェントをデプロイし、管理するために、Google Cloud Deployment Manager ではなく Google Cloud Infrastructure Manager（IM）を使用するようになりました。この変更は、Googleが廃止する予定であるためです。 link:https://docs.cloud.google.com/deployment-manager/docs/deprecations["クラウドデプロイメントマネージャー"]。

* 4.2.0 以降の新しいエージェントはすべて Infrastructure Manager を使用するため、デプロイメントに使用するユーザー アカウントとサービス アカウントの両方の権限を更新する必要があります。 link:https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-gcp.html#gcp-permissions-change-log["権限変更ログを表示します。"^]
* エージェントをデプロイすると、デプロイ ファイルを保存するための Google Cloud バケットも作成されます。


.コンソールエージェントの構成チェックの改善
* コンソール エージェントは、構成チェックを実行するときに、非推奨のエンドポイントをチェックするようになりました。4.0.0 以降の新しいエンドポイント リストに更新していない場合、システムが以前のエンドポイント リストにアクセスできる場合はインストールが成功します。 link:https://docs.netapp.com/us-en/console-setup-admin/reference-networking-saas-console-previous.html#update-endpoint-list["コンソール エージェントに必要なエンドポイントの詳細について説明します。"^]
* コンソールまたはエージェントのメンテナンス コンソールからインストールされたコンソール エージェントの構成チェックを実行し、接続を確認して問題をトラブルシューティングします。 link:https://docs.netapp.com/us-en/console-setup-admin/task-troubleshoot-agent.html#verify-network-access["コンソール エージェントで構成チェックを実行する方法を学習します。"^]


.NetApp Consoleからエージェントソフトウェアを直接ダウンロード
エージェントを手動でインストールする必要がある場合は、 NetAppサポート サイトに加えて、 NetApp Consoleから直接エージェント ソフトウェアにアクセスできます。 link:https://docs.netapp.com/us-en/console-setup-admin/task-install-agent-on-prem.html#install-the-console-agent-manually["NetApp Consoleからコンソール エージェント ソフトウェアを直接ダウンロードする方法を説明します。"^]



==== NetApp Console管理

このリリースには以下が含まれます。

.資格情報の有効期限切れに関する通知を設定する機能
サービス アカウントとフェデレーションの資格情報の有効期限が切れた場合の通知を設定します。7日間または30日間から選択してください。コンソールに通知が表示され、適切なロールを持つユーザーに電子メールが送信されます。組織管理者はサービス アカウント通知を受け取ります。組織管理者、フェデレーション管理者、およびフェデレーション閲覧者はフェデレーション通知を受け取ります。

.フェデレーションを有効にすると、ローカルログインは利用できなくなります
コンソール組織に対してフェデレーションを有効にすると、ユーザーはローカル ログインを使用できなくなり、フェデレーション ログインに送信されます。

.ストレージ管理ページの使いやすさの向上
ONTAPオンプレミス システム (および FSx for ONTAP) に関する詳細情報を、ストレージ管理ページから簡単に表示および管理できるようになりました。

* *Discoverable systems* ページでは、利用可能なシステムのタブ表示から概要情報が分離されているため、検出可能なシステムに関する包括的な情報を簡単に表示できます。




=== オンプレミスのONTAPクラスタ



==== NetApp ConsoleからONTAPシステムを表示する際の使いやすさの向上 (標準モードのみ)

NetApp Consoleの *システム* ページでは、ボリュームとクラスタを管理する際の明確さと使いやすさが向上しました。これらの更新により、新しいONTAPバージョンの System Manager とのエクスペリエンスがより密接になり、ナビゲーションが簡素化されます。

.ONTAPバージョン 9.5 以降に含まれるクラスタ容量 (コンソール標準モードのみ)
*システム > 概要* ページには、 ONTAP 9.5 以降を実行しているクラスタのクラスタ サイズとONTAPバージョンが表示されます。

制限モードのNetApp ConsoleまたはONTAPバージョン 9.5 以下の場合、ボリュームのプロビジョニング情報は変更されません。

.オンプレミスのONTAPクラスタが 20 個を超える場合、システム ページのボリューム タブはデフォルトでグリッド ビューになります。
NetApp Consoleで管理されているオンプレミスのONTAPクラスターが 20 個を超える場合、ナビゲーションを容易にするために、*ボリューム* タブはデフォルトでグリッド ビューになります。カードビューは無効です。

この変更は標準モードのみ、およびONTAPバージョン 9.6 以降に適用されます。



== 2025年12月9日



=== ディザスタ リカバリ



==== フォルダ階層の保持

デフォルトでは、ディザスタ リカバリはフェイルオーバー時に VM インベントリ階層 (フォルダー構造) を保持します。回復対象に必要なフォルダーがない場合、Disaster Recovery によってフォルダーが作成されます。

新しい親 VM フォルダを指定するか、[**元のフォルダ階層を保持**] オプションのチェックを外すことで、この設定を上書きできるようになりました。

詳細については、 link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html["レプリケーションプランを作成する"]。



==== 合理化されたコンソールエージェントの更新

災害復旧では、作業環境で複数のコンソール エージェントを使用するための合理化されたプロセスがサポートされるようになりました。コンソール エージェントを切り替えるには、vCenter 構成を編集し、資格情報を再検出し、新しいコンソール エージェントを使用するようにレプリケーション プランを更新する必要があります。

詳細については、 link:https://docs.netapp.com/us-en/data-services-disaster-recovery/reference/switch-console-agent.html["スイッチコンソールエージェント"]。



== 2025年12月8日



=== バックアップとリカバリ



==== VMware ワークロードのプレビュー機能強化

VMware ワークロードのプレビュー リリースでは、次の拡張機能が導入されています。

* バックアップとスナップショットを別の場所に復元できるようになりました。これは、異なる VMware vCenter 展開、VMware ESXi ホスト、または VMware データストア上の VM のバージョンを管理する場合に便利です。


link:br-use-vmware-restore.html["NetApp Backup and Recoveryを使用したVMware VMの復元の詳細"]。

* 特定の VMware 仮想ディスク (VMDK イメージ) をプライマリまたはセカンダリの場所から復元できるようになり、VM データの復元をより細かく制御できるようになりました。


link:br-use-vmware-restore-vmdks-from-backups.html["NetApp Backup and Recoveryを使用したVMware仮想ディスクの復元の詳細"]。



=== データ分類



==== バージョン1.49

この Data Classification リリースには、バグ修正と次の更新が含まれています。

.ヘルスモニタリングダッシュボードで指標とパフォーマンスを監視する
データ分類では、ヘルス モニタリング ダッシュボードが提供されるようになり、リソースのリアルタイム モニタリングと、メモリ使用量、ディスク使用量、ディスク使用率などの分析情報が提供されます。ヘルス モニタリング ダッシュボードから得られる分析情報を活用することで、展開のインフラストラクチャを確認し、ストレージとパフォーマンスを最適化するための分析情報を得ることができます。

詳細については、 link:https://docs.netapp.com/us-en/data-services-data-classification/task-health-monitor.html["データ分類の健全性を監視する"]。

.読み込みパフォーマンスの向上
データ分類のすべてのページの読み込みパフォーマンスが向上し、より効率的なユーザー エクスペリエンスが実現しました。



=== ランサムウェア耐性



==== 拡張機能のブロックはワークロードレベルで有効になります

拡張機能のブロックを有効にすると、ストレージ VM レベルではなくワークロード レベルで有効になります。



==== ユーザー行動アラートステータスの編集

Ransomware Resilience では、ユーザー行動アラートのステータスを編集できるようになりました。アラートを手動で解除したり解決したりできます。

詳細については、 link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-alert.html["ランサムウェア耐性のアラートを管理する"^]。



==== 複数のコンソールエージェントのサポート

Ransomware Resilience では、複数のコンソール エージェントを使用して同じシステムを管理することがサポートされるようになりました。

コンソールエージェントの詳細については、以下を参照してください。link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-start-setup.html["コンソールエージェントを作成する"] 。



=== Cloud Volumes ONTAP



==== Azure の Premium SSD v2 ディスクのパフォーマンスを向上させる機能

IOPS およびスループット パラメーターを変更することで、Azure の Premium SSD v2 マネージド ディスクのパフォーマンスを向上できるようになりました。この機能を使用すると、ワークロード要件に基づいてシステムのストレージ パフォーマンスを最適化できます。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-perf-params-azure.html["Azure のCloud Volumes ONTAPの Premium SSD v2 ディスク パフォーマンスを管理する"^]。



==== Essentialsライセンスの超過料金の簡素化

Cloud Volumes ONTAPマーケットプレイスの年間契約/プライベート オファーの場合、Essentials ライセンスの超過計算が Bring Your Own License (BYOL) パッケージと一致するようになりました。以前は、超過分は、Essentials パッケージそのものに対して、時間単位のマーケットプレイス料金で請求されていました。現在、マーケットプレイスの年間契約に複数の Essentials パッケージが含まれている場合、 NetApp Consoleは、サブスクリプション内のより高額な Essentials パッケージの利用可能な容量に対して、Essentials パッケージの超過料金を請求します。これにより、Essentials パッケージの超過計算が簡素化され、BYOL ライセンスからサブスクリプション ベースのモデルへのスムーズな移行が保証されます。

https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing-charging.html#how-overages-are-charged-for-essentials-licenses["Essentialsライセンスの超過料金の請求方法"^]



==== Azure Edsv6 サイズ シリーズのサポート

Cloud Volumes ONTAP 9.17.1 以降では、新しいCloud Volumes ONTAPインスタンス用に、 NetApp Consoleを通じて Azure Edsv6 シリーズ VM をデプロイできます。Cloud Volumes ONTAP 9.17.1 以降では、新しいデプロイメントでは第 2 世代 VM のみがサポートされます。これらの第 2 世代マシンは、Unified Extensible Firmware Interface (UEFI)、Azure Boost システム、NVMe などの最新テクノロジと互換性があります。これらは、データベース サーバーや分析エンジンなど、高速なローカル ストレージを必要とするメモリを大量に消費するシステムやアプリケーションに最適です。

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html#supported-configurations-by-license["Azure でサポートされるCloud Volumes ONTAPの構成"^]



=== Keystone

NetApp ConsoleのKeystoneダッシュボードの新しい機能強化:



==== 累積バースト容量ラベルの名前を変更しました

ラベル *Accrued burst capacity* の名前が *Accrued burst* に変更されます。



== 2025年12月1日



=== ディザスタ リカバリ



==== Google Cloud NetApp Volumesを使用した Google Cloud VMware Engine のサポート

NetApp Disaster Recovery、移行、フェイルオーバー、フェイルバック、テスト操作にGoogle Cloud NetApp Volumesを使用する Google Cloud VMware Engine をサポートするようになりました。この統合により、オンプレミス環境と Google Cloud 間でシームレスな障害復旧ワークフローが可能になります。

必ず確認してくださいlink:https://docs.netapp.com/us-en/data-services-disaster-recovery/get-started/dr-prerequisites.html["前提条件"]そしてlink:https://docs.netapp.com/us-en/data-services-disaster-recovery/release-notes/dr-limitations.html["制限事項"]Google Cloud 向け。



== 2025年11月27日



=== Google Cloud NetApp Volumes



==== Google Cloud Platform の認証情報の変更

お客様がより多くのGoogle Cloud NetApp Volumesシステムをセットアップして承認するにつれて、認証情報の管理方法が変わりました。

NetApp Volumes システムの認証情報は、Cloud Key Management サービスなどの Google クラウド バックエンドに保存されるようになり、新しいシステムを作成するときにサービス アカウントの偽装認証情報が使用されます。



== 2025年11月24日



=== Keystone

NetApp ConsoleのKeystoneダッシュボードの新しい機能強化:



==== カバレッジギャップサブスクリプションの追跡ID

*モニタリング > アラート モニター* の *カバレッジの完了* 通知ボックスで、各サブスクリプションのサブスクリプション番号の横に追跡 ID が表示されるようになりました。



== 2025年11月17日



=== ONTAP向け Amazon FSX



==== AWS Lambda リンクを使用する場合に利用できる System Manager

ONTAP System Manager インターフェイスを AWS Lambda リンクと組み合わせて使用​​すると、高度なONTAP操作を実行できます。これにより、System Manager でコンソール エージェントを使用する代わりに、コンソールから直接 FSx for ONTAPファイル システムを管理できるようになります。 link:https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["高度なONTAP操作のためのリンクの使用について学習します"^]



== 2025年11月11日



=== ONTAP向け Amazon FSX



==== オンプレミスのONTAPシステムと FSx for ONTAPファイルシステム間のレプリケーションのサポート

NetApp Consoleシステム ページから、オンプレミスのONTAPシステムと FSx for ONTAPファイル システム間のデータ レプリケーションを利用できます。

link:https://docs.netapp.com/us-en/storage-management-fsx-ontap/use/task-manage-fsx-systems.html#replicate-data["データを複製する"]



== 2025年11月10日



=== Licenses and subscriptions



==== 請求設定を管理する

NetApp Console内で直接 *課金設定* を設定および管理できるようになりました。この機能強化により、管理者は、直接のNetAppライセンス、クラウド マーケットプレイスのサブスクリプション、およびKeystone契約全体で容量の使用状況、更新、およびコストの請求方法を定義および表示できるようになります。

詳細については、link:https://docs.netapp.com/us-en/console-licenses-subscriptions/concept-billing-preferences.html["請求設定に関するドキュメント"^] 。



=== コンソールのセットアップと管理



==== コンソールエージェント 4.1.0

コンソール エージェントのこのリリースには、セキュリティの改善、バグ修正、および次の機能が含まれています。

4.1.0 リリースは、標準モードと制限モードで利用できます。

.エージェントステータスインジケーターの名前を変更しました
コンソール エージェントのステータス インジケーターの名前を *アクティブ* と *非アクティブ* から *接続済み* と *切断済み* に変更し、目的をより明確にしました。

.Red Hat Enterprise Linux (RHEL) 9.6 および Podman 5.4.0 のサポート
コンソール エージェントを手動でインストールする場合、エージェントは Podman 5.4.0 を搭載した RHEL 9.6 をサポートするようになりました。さらに、RHEL 9 以降を使用する場合、 NetApp はpodman-compose 1.5.0 をサポートします。link:https://docs.netapp.com/us-en/console-setup-admin/task-install-agent-on-prem.html["オペレーティング システムの要件を表示"]。



==== NetApp Console管理

このリリースには以下が含まれます。

.NetApp Console通知用の新しいメールアドレス
NetApp Console通知を送信する電子メール アドレスが *service@console.bluexp.netapp.com* から *service@console.netapp.com* に変更されました。NetApp、NetApp Consoleの電子メール通知を引き続き受信できるように、電子メール ルールを更新して *service@console.netapp.com* を許可することを推奨しています。



=== データ分類



==== バージョン1.48

この Data Classification リリースには、バグ修正、セキュリティの改善、パフォーマンスの強化が含まれています。

.スキャンの進行状況の明確化を強化
スキャン構成には、スキャン完了に関する改善された分析情報が含まれるようになりました。以前は、スキャンの進行中にのみ進行状況バーが表示されていました。スキャンが正常に完了したことを確認できるように、完了後も進行状況バーが表示されるようになりました。マップおよびスキャンされたファイルの数を表示することもできます。

スキャン設定の詳細については、 link:https://docs.netapp.com/us-en/data-services-data-classification/task-managing-repo-scanning.html#view-the-scan-status-for-your-repositories["リポジトリのNetApp Data Classificationスキャン設定を変更する"^]。



=== ディザスタ リカバリ



==== カスケードフェイルオーバーのサポート

ONTAPでカスケード関係を設​​定し、そのレプリケーション関係の任意のレッグを使用して災害復旧を行うことができます。



==== 登録中に VMware ハードウェア サポートをダウングレードする

ディザスタ リカバリでは、登録中に VMware ハードウェアを vSphere の以前のバージョンにダウングレードできるようになりました。これは、ソース ESX ホストが災害復旧サイトよりも新しいバージョンを実行している場合に役立ちます。

詳細については、 link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html#select-vcenter-servers["NetApp Disaster Recoveryでレプリケーションプランを作成する"]。



==== 正常なシャットダウン

災害復旧では、VM の電源をオフにするのではなく、VM を正常にシャットダウンするようになりました。特定の VM の電源を切るのに 10 分以上かかる場合、Disaster Recovery によってその VM の電源がオフになります。



==== バックアップ前のスクリプトのサポート

バックアップを作成する前に実行するカスタム スクリプトをフェイルオーバー ワークフローに挿入できるようになりました。バックアップ前のスクリプトを使用すると、スナップショットが複製される前に VM の状態を制御し、VM を移行用に準備することができます。たとえば、フェイルオーバー後に別のスクリプトを使用して再マウントされる NFS マウントをアンマウントするスクリプトを挿入できます。

詳細については、 link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html#select-vcenter-servers["NetApp Disaster Recoveryでレプリケーションプランを作成する"]。



=== ランサムウェア耐性

このリリースには、全般的な機能強化と改善が含まれています。



=== Cloud Volumes ONTAP



==== 強化されたNVMe-TCPサポート

以前は、NVMe-TCP 経由でCloud Volumes ONTAPインスタンスをデプロイする場合、デプロイ前に NVMe ライセンスを手動で取得して適用する必要がありました。このアップデートにより、 Cloud Volumes ONTAP は導入時に必要な NVMe ライセンスを自動的にインストールするようになり、セットアップ プロセスが簡素化されます。

ライセンスが不足している既存の NVMe-TCP デプロイメントの場合、 Cloud Volumes ONTAP はライセンスを自動的に適用します。ライセンスを有効にするには、システムを再起動する必要があります。

詳細については、 https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-client-protocols.html#nvme-tcp["Cloud Volumes ONTAPでサポートされているクライアント プロトコル: NVMe-TCP"^] 。



=== Keystone

NetApp ConsoleのKeystoneダッシュボードの新しい機能強化:



==== 補償通知ボックスを入力してください

*監視*ページの*アラート モニター*タブには、カバレッジ ギャップが存在する場合に表示される*カバレッジの完了*通知ボックスが含まれています。このボックスには、容量または有効期限モニターが不足しているサブスクリプションと、サブスクリプションのないモニターがリストされます。ギャップに対処するには、既存のモニターにサブスクリプションを追加したり、新しいモニターを作成したり、使用されていないモニターを削除したりします。詳細については、 link:https://docs.netapp.com/us-en/keystone-staas/integrations/monitoring-alert-monitors.html#manage-coverage-gaps["アラートモニターのカバレッジギャップを管理する"]。
