---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, agent, amazon fsx for ontap, azure netapp files, cloud sync, e-series, global file cache, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery, netapp console, console' 
summary: NetApp Consoleの一部である機能とデータ サービスに対する最新の変更について説明します。 
---
= NetApp Consoleの最近の変更
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Consoleの一部である機能とデータ サービスに対する最新の変更について説明します。完全なリリース履歴については、link:release-notes-index.html["リリースノート全文"]個々のサービスごとに。



== 管理機能

このセクションでは、 NetApp Console管理機能に関連する新機能 (組織、識別とアクセス、コンソール エージェント、クラウド プロバイダーの資格情報など) について説明します。



== アラート



== Amazon FSx for ONTAP



== Amazon S3 ストレージ



== Azure BLOB ストレージ



== Azure NetApp Files



== バックアップとリカバリ



== データ分類



== Cloud Volumes ONTAP



== コピーと同期



== デジタルアドバイザー



== Licenses and subscriptions



=== 2025年10月6日



==== BlueXPはNetApp Consoleになりました

NetApp Consoleは、強化され再構築されたBlueXP基盤上に構築され、オンプレミスとクラウド環境全体にわたるエンタープライズ グレードのNetAppストレージとNetApp Data Servicesの集中管理を提供し、リアルタイムの分析情報、より高速なワークフロー、および高度なセキュリティとコンプライアンスを備えた簡素化された管理を実現します。

変更内容の詳細については、link:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["NetApp Consoleのリリースノート"] 。



=== 2025年3月10日



==== サブスクリプションを削除する機能

サブスクリプションを解除した場合は、デジタル ウォレットからサブスクリプションを削除できるようになりました。



==== マーケットプレイスサブスクリプションの使用済み容量を表示する

PAYGO サブスクリプションを表示するときに、サブスクリプションの消費容量を表示できるようになりました。



=== 2025年2月10日

BlueXP digital walletは使いやすさを考慮して再設計され、追加のサブスクリプションとライセンスの管理機能を提供するようになりました。



==== 新しい概要ダッシュボード

デジタル ウォレットのホームページには、 NetAppライセンスと Marketplace サブスクリプションの更新されたダッシュボードがあり、特定のサービス、ライセンスの種類、必要なアクションをドリルダウンできます。



==== 資格情報へのサブスクリプションの構成

BlueXP digital walletでは、プロバイダー資格情報へのサブスクリプションを設定できるようになりました。通常、これはマーケットプレイスのサブスクリプションまたは年間契約に初めて加入するときに行います。以前は、サブスクリプションの資格情報の変更は、「資格情報」ページでのみ実行できました。



==== サブスクリプションを組織に関連付ける

サブスクリプションが関連付けられている組織をデジタル ウォレットから直接更新できるようになりました。



==== Cloud Volume ONTAPライセンスの管理

Cloud Volumes ONTAPライセンスは、ホームページまたは *直接ライセンス* タブから管理できるようになりました。サブスクリプション情報を表示するには、「*マーケットプレイス サブスクリプション*」タブを使用します。



=== 2024年3月5日



==== BlueXP disaster recovery

BlueXP digital walletでは、BlueXP disaster recoveryのライセンスを管理できるようになりました。ライセンスを追加したり、ライセンスを更新したり、ライセンス容量の詳細を表示したりできます。

https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["BlueXPデータサービスのライセンスを管理する方法を学びます"]



=== 2023年7月30日



==== 使用状況レポートの機能強化

Cloud Volumes ONTAP使用状況レポートにいくつかの改善が加えられました。

* 列名に TiB 単位が含まれるようになりました。
* シリアル番号用の新しい _node(s)_ フィールドが追加されました。
* ストレージ VM 使用状況レポートに新しい _ワークロード タイプ_ 列が追加されました。
* ストレージ VM およびボリュームの使用状況レポートに作業環境名が含まれるようになりました。
* ボリューム タイプ _file_ のラベルが _Primary (読み取り/書き込み)_ に変更されました。
* ボリューム タイプ「_secondary_」のラベルが「_Secondary (DP)_」に変更されました。


使用状況レポートの詳細については、以下を参照してください。 https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-capacity-licenses.html#download-usage-reports["使用状況レポートをダウンロードする"] 。



== ディザスタ リカバリ



== Eシリーズシステム



== ライフサイクルプランニング



== エッジキャッシュ

エッジ キャッシング サービスは 2024 年 8 月 7 日に削除されました。



== Google Cloud NetApp Volumes



== Google Cloud Storage



== Keystone



== Kubernetes

Kubernetes クラスターの検出と管理のサポートは、2024 年 8 月 7 日に削除されました。



== 移行レポート

移行レポート サービスは 2024 年 8 月 7 日に削除されました。



== オンプレミスのONTAPクラスター



== 運用の回復力

運用回復力機能は 2025 年 8 月 22 日に削除されました。



== ランサムウェア耐性



== 修正策

修復サービスは 2024 年 4 月 22 日に削除されました。



== レプリケーション



== ソフトウェアアップデート



== StorageGRID



== クラウド階層化



=== 2025年10月6日



==== BlueXP tieringはNetApp Cloud Tiering に変更されました

BlueXP tieringはNetApp Cloud Tieringに名前が変更されました。



==== BlueXPはNetApp Consoleになりました

NetApp Consoleは、強化され再構築されたBlueXP基盤上に構築され、オンプレミスとクラウド環境全体にわたるエンタープライズ グレードのNetAppストレージとNetApp Data Servicesの集中管理を提供し、リアルタイムの分析情報、より高速なワークフロー、および高度なセキュリティとコンプライアンスを備えた簡素化された管理を実現します。

変更内容の詳細については、link:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["NetApp Consoleのリリースノート"] 。



=== 2023年8月9日



==== バケット名にカスタムプレフィックスを使用する

以前は、バケット名を定義するときに、デフォルトの「fabric-pool」プレフィックス (例: _fabric-pool-bucket1_) を使用する必要がありました。バケットに名前を付けるときにカスタムプレフィックスを使用できるようになりました。この機能は、データを Amazon S3 に階層化する場合にのみ使用できます。 https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html#prepare-your-aws-environment["詳細情報"] 。



==== すべてのBlueXPコネクタでクラスターを検索

複数のコネクタを使用して環境内のすべてのストレージ システムを管理している場合、階層化を実装する一部のクラスターが異なるコネクタに存在する可能性があります。どのコネクタが特定のクラスターを管理しているかわからない場合は、クラウド階層化を使用してすべてのコネクタを検索できます。 https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#search-for-a-cluster-across-all-bluexp-connectors["詳細情報"] 。



=== 2023年7月4日



==== 非アクティブなデータを転送するための帯域幅を調整する

Cloud Tiering をアクティブ化すると、 ONTAP は無制限のネットワーク帯域幅を使用して、クラスター内のボリュームからオブジェクト ストレージに非アクティブなデータを転送できます。階層化トラフィックが通常のユーザー ワークロードに影響を与えていることに気付いた場合は、転送中に使用できる帯域幅の量を調整できます。 https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#changing-the-network-bandwidth-available-to-upload-inactive-data-to-object-storage["詳細情報"] 。



==== 通知センターに表示される階層化イベント

階層化イベント「ストレージ効率を高めるためにクラスター <name> からオブジェクト ストレージに追加のデータを階層化します」は、クラスターが階層化しているコールド データが 20% 未満の場合 (階層化しているデータがまったくないクラスターを含む) に通知として表示されるようになりました。

この通知は、システムの効率を高め、ストレージ コストを節約するための「推奨事項」です。リンクを提供します https://www.netapp.com/data-services/tiering/tco-calculator/["クラウド階層化の総所有コストと節約額の計算ツール"^]コスト削減の計算に役立ちます。



== ボリュームキャッシュ



== ワークロードファクトリー



=== 2025年10月6日



==== BlueXP workload factoryがNetApp Workload Factoryに

BlueXP は、データ インフラストラクチャの管理における役割をより適切に反映するために、名前が変更され、再設計されました。その結果、 BlueXP workload factoryの名前がNetApp Workload Factoryに変更されました。



==== MCP との Ask Me 統合

Workload Factory の AI アシスタントである Ask Me は、Model Context Protocol (MCP) と統合されています。  MCP を使用することで、Ask Me は外部環境と安全にインターフェイスし、API ツールにクエリを実行して、特定のストレージ環境に合わせた応答を提供します。



=== 2025年10月5日



==== ストレージの新しい通知

NetApp Workload Factory通知サービスには、ストレージの Well-Architected の問題に関する通知が含まれています。

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["NetApp Workload Factoryの通知"]



=== 2025年9月9日



==== ストレージの新しい通知

BlueXP workload factory通知サービスには、ストレージの自動容量管理に関する通知が含まれています。

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["BlueXP workload factoryの通知"]
