= コンソールエージェント 4.3.0
:allow-uri-read: 




=== コンソールエージェント 4.3.0

4.3.0 リリースでは、標準モードと制限モードの両方がサポートされています。

コンソール エージェントのこのリリースには、セキュリティの改善、バグ修正、および次の機能が含まれています。

.コンソールエージェントのネットワーク接続を検証する機能
接続された Console エージェントのネットワーク接続をNetApp Console から直接検証できるようになりました。この機能は、Console エージェントの接続性を検証し、問題のトラブルシューティングに役立ちます。これは、Console エージェントのメンテナンスコンソールのコマンドラインインターフェース（CLI）からネットワーク診断を実行できる既存の機能に加えて提供されます。

link:https://docs.netapp.com/us-en/console-setup-admin/task-troubleshoot-agent.html#verify-network-access["NetApp Consoleから構成を実行する方法を学習します。"]



=== NetApp Console管理

このリリースには以下が含まれます。

.NetApp Consoleでのフェデレーション グループに対するロールベースのアクセス
NetApp Consoleは、フェデレーション グループ (Active Directory グループなど) へのロールの割り当てをサポートしており、管理者は組織の ID プロバイダー (IdP) のグループ メンバーシップに基づいてユーザーのオンボーディングとオフボーディングを自動化できます。この機能により、管理オーバーヘッドが削減され、グループ メンバーシップの変更に応じてコンソール アクセスが即座に更新されるため、安全で一貫したアクセスが確保されます。

link:https://docs.netapp.com/us-en/console-setup-admin/task-iam-manage-members-permissions.html#add-a-federated-group-to-your-organization["組織にフェデレーション グループへのアクセスを提供する方法を学習します。"]

.NetApp Consoleが制限モードの場合のフェデレーションのサポート
制限モードになっているNetApp Console組織に対してフェデレーションを有効にできるようになりました。これにより、ユーザーは制限モードのセキュリティ上の利点を維持しながら、企業の資格情報を使用してコンソールにログインできるようになります。

.読み取り専用モード
NetApp Console組織を読み取り専用モードに設定できます。読み取り専用モードでは、ユーザーはリソースと設定を表示できますが、変更することはできません。組織管理者またはスーパー管理者は、組織に対して読み取り専用モードを有効にすることができます。読み取り専用モードが有効になっている場合、管理者ロールを持つユーザーは、必要に応じて変更を加えるために手動で権限を昇格する必要があります。

link:https://docs.netapp.com/us-en/console-setup-admin/task-enable-read-only-mode.html["コンソール組織で読み取り専用モードを有効にする方法を学習します。"]

link:https://docs.netapp.com/us-en/console-setup-admin/task-user-settings.html["組織が読み取り専用モードの場合に役割を昇格させる方法を学習します。"]
