= コンソールエージェント 4.3.0
:allow-uri-read: 




=== コンソールエージェント 4.3.0

4.3.0 リリースでは、標準モードと制限モードの両方がサポートされています。

コンソール エージェントのこのリリースには、セキュリティの改善、バグ修正、および次の機能が含まれています。

.コンソールエージェントのネットワーク接続を検証する機能
接続されたコンソール エージェントのネットワーク接続をNetApp Consoleから直接検証できるようになりました。この機能は、接続の検証とコンソール エージェントの問題のトラブルシューティングに役立ちます。

link:https://docs.netapp.com/us-en/console-setup-admin/task-troubleshoot-agent.html#verify-network-access["コンソール エージェントで構成チェックを実行する方法を学習します。"]



=== NetApp Console管理

このリリースには以下が含まれます。

.NetApp Consoleが制限モードの場合のフェデレーションのサポート
制限モードになっているNetApp Console組織に対してフェデレーションを有効にできるようになりました。これにより、ユーザーは制限モードのセキュリティ上の利点を維持しながら、企業の資格情報を使用してコンソールにログインできるようになります。

.読み取り専用モード
NetApp Console組織を読み取り専用モードに設定できます。読み取り専用モードでは、ユーザーはリソースと設定を表示できますが、変更することはできません。組織管理者またはスーパー管理者は、組織に対して読み取り専用モードを有効にすることができます。読み取り専用モードが有効になっている場合、管理者ロールを持つユーザーは、必要に応じて変更を加えるために手動で権限を昇格する必要があります。

link:https://docs.netapp.com/us-en/console-setup-admin/task-enable-read-only-mode.html["コンソール組織で読み取り専用モードを有効にする方法を学習します。"]

link:https://docs.netapp.com/us-en/console-setup-admin/task-user-settings["組織が読み取り専用モードの場合に役割を昇格させる方法を学習します。"]
