= Google Cloud のフラッシュ キャッシュと高速書き込みのサポート
:allow-uri-read: 


コネクタの 3.9.32 リリースでは、次の変更が導入されました。



=== Google Cloud のフラッシュ キャッシュと高速書き込みのサポート

Google Cloud for Cloud Volumes ONTAP 9.13.1 以降では、Flash Cache と高速書き込み速度を個別に有効にできます。サポートされているすべてのインスタンス タイプで、高速書き込み速度を利用できます。Flash Cache は次のインスタンス タイプでサポートされています。

* n2-標準-16
* n2-標準-32
* n2-標準-48
* n2-標準-64


これらの機能は、単一ノードと高可用性ペアの両方の展開で個別に、または一緒に使用できます。

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-gcp.html["Google Cloud でCloud Volumes ONTAPを起動する"^]



=== 使用状況レポートの機能強化

使用状況レポート内に表示される情報にさまざまな改善が加えられました。使用状況レポートの機能強化は次のとおりです。

* 列名に TiB 単位が含まれるようになりました。
* シリアル番号用の新しい「ノード」フィールドが追加されました。
* ストレージ VM 使用状況レポートに新しい「ワークロード タイプ」列が追加されました。
* ストレージ VM およびボリュームの使用状況レポートに作業環境名が含まれるようになりました。
* ボリューム タイプ「ファイル」のラベルが「プライマリ (読み取り/書き込み)」になりました。
* ボリューム タイプ「セカンダリ」のラベルが「セカンダリ (DP)」に変更されました。


使用状況レポートの詳細については、以下を参照してください。link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-capacity-licenses.html#download-usage-reports["使用状況レポートをダウンロードする"^] 。
