= S3 構成のONTAPシステム上のバケットにボリュームをバックアップするためのサポートが追加されました
:allow-uri-read: 


[IMPORTANT]
====
* 重要なセキュリティ強化により、パブリック クラウド環境内のバックアップおよびリカバリ リソースを管理するために、コネクタでは追加のエンドポイントへの送信インターネット アクセスが必要になりました。このエンドポイントがファイアウォールの「許可」リストに追加されていない場合は、UI に「サービスを利用できません」または「サービス ステータスを判別できませんでした」というエラーが表示されます。
+
\https://netapp-cloud-account.auth0.com

* Cloud Volumes ONTAPとBlueXP backup and recoveryをバンドルできる「CVO Professional」パッケージを使用する場合は、バックアップとリカバリの PAYGO サブスクリプションが必要になりました。これは過去には必要ありませんでした。対象となるCloud Volumes ONTAPシステムのバックアップおよびリカバリ サブスクリプションには料金は発生しませんが、新しいボリュームでバックアップを構成する場合は必要です。


====


=== S3 構成のONTAPシステム上のバケットにボリュームをバックアップするためのサポートが追加されました

これで、Simple Storage Service (S3) 用に設定されたONTAPシステムを使用して、ボリュームをオブジェクト ストレージにバックアップできるようになりました。これは、オンプレミスのONTAPシステムとCloud Volumes ONTAPシステムの両方でサポートされています。この構成は、クラウド展開およびインターネット アクセスのないオンプレミスの場所 (「プライベート」モード展開) でサポートされます。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-ontap-s3.html["詳細情報"] 。



=== 保護されたボリュームの既存のスナップショットをバックアップファイルに含めることができるようになりました

これまでは、最新の Snapshot コピーから開始するのではなく、読み取り/書き込みボリュームの既存の Snapshot コピーをオブジェクト ストレージへの初期バックアップ ファイルに含めることができました。読み取り専用ボリューム (データ保護ボリューム) からの既存のスナップショット コピーは、バックアップ ファイルに含まれていません。これで、「DP」ボリュームのバックアップ ファイルに古いスナップショット コピーを含めることを選択できるようになりました。

バックアップ ウィザードでは、バックアップ手順の最後にプロンプトが表示され、そこでこれらの「既存のスナップショット」を選択できます。



=== BlueXP backup and recoveryは、将来追加されるボリュームの自動バックアップをサポートしなくなりました。

以前は、バックアップ ウィザードでボックスをオンにして、選択したバックアップ ポリシーをクラスターに追加されるすべての将来のボリュームに適用できました。この機能は、ユーザーからのフィードバックとこの機能の使用頻度の低さに基づいて削除されました。クラスターに追加された新しいボリュームのバックアップを手動で有効にする必要があります。



=== ジョブ監視ページが新しい機能で更新されました

ジョブ監視ページでは、3-2-1 バックアップ戦略に関連する詳細情報が提供されるようになりました。このサービスは、バックアップ戦略に関連する追加のアラート通知も提供します。

「バックアップ ライフサイクル」タイプ フィルターの名前が「保持」に変更されました。このフィルターを使用して、バックアップのライフサイクルを追跡し、すべてのバックアップ コピーの有効期限を識別します。  「保持」ジョブ タイプは、BlueXP backup and recoveryによって保護されているボリューム上で開始されたすべてのスナップショット削除ジョブをキャプチャします。

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["更新されたジョブモニターの詳細"] 。
